name: json_delta
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/korenminchev/json_delta

environment:
  sdk: '>=2.12.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  json_patch: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
