name: json_delta_tool
description: A simple tool for calculating the delta (difference) between 2 json objects with the same schema.
version: 1.0.0
repository: https://github.com/korenminchev/json_delta

environment:
  sdk: '>=2.12.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  json_patch: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
